[profile.default]
src = "src"
out = "out"
libs = ["lib", "lib/ds-libs/lib"]

fs_permissions = [{ access = "read-write", path = "./" }]

optimizer = true
optimizer_runs = 1000000
--compiler-version = "v0.8.23+commit.f704f362"
# yul = false

[fmt]
line_length = 100
tab_width = 2
int_types = "short"


[rpc_endpoints]
goerli = "${RPC_URL}"
arbitrum-sepolia = "${RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
